#.........................................................................
# VERSION "@(#)$Header$"
#      EDSS/Models-3 I/O API Version 3.
#.........................................................................
# COPYRIGHT
#       (C) 1992-2002 MCNC and Carlie J. Coats, Jr., and
#       (C) 2003-2004 by Baron Advanced Meteorological Systems.
#       Distributed under the GNU Lesser PUBLIC LICENSE version 2.1
#       See file "LGPL.txt" for conditions of use.
#.........................................................................
#  Environment Variables:
#       BIN     machine/OS/compiler/mode type. Shows up as suffix
#               for "Makeinclude.$(BIN)" to determine compilation
#               flags, and in $(OBJDIR) and $(INSTALL) to determine
#               binary directories
#       INSTALL installation-directory root, used for "make install":
#               "libioapi.a" and the tool executables will be installed
#               in $(INSTALL)/$(BIN)
#.........................................................................
#  Directories:
#       $(BASEDIR)  is the root directory for the I/O API library source,
#                   the M3Tools and M3Test source,the  HTML documentation,
#                   and the (machine/compiler/flag-specific) binary
#                   object/library/executable directories.
#       $(HTMLDIR)  is the web documentation
#       $(IODIR)    is the I/O API library source
#       $(TOOLDIR)  is the "M3TOOLS" source
#       $(TESTDIR)  is the "IOTESTS" source and binaries
#       $(OBJDIR)   is the current machine/compiler/flag-specific
#                   build-directory
#       $(INSTALL)  installation-directory root, used for "make install":
#                   "libioapi.a" and the tool executables will be installed
#                   in $(INSTALL)/$(BIN)
#       object/library/executable directory
#.........................................................................
# Note On Library Versions:
#       Environment variable "BIN" specifies library version up to
#       link- and compile-flag compatibility.  Dependecies upon machine,
#       OS, and compiler are found in file "Makeinclude.$(BIN).
#       IN PARTICULAR, pay attention to the notes for various versions
#       that may be built for Linux x86 with the Portland Group
#       compilers:  see comments in $(IODIR)/Makeinclude.Linux2_x86pg
#.........................................................................
# Special Make-targets
#       all:      OBJDIR, FIXDIR, libioapi.a, and executables, with
#                 coupling mode enabled
#       nocpl:    OBJDIR, FIXDIR, libioapi.a, and executables, with
#                 coupling mode disabled
#       f77:      OBJDIR, FIXDIR, libioapi.a, and F77-based executables
#       nocpl77:  OBJDIR, FIXDIR, libioapi.a, and F77-based executables,
#                 with coupling mode disabled
#       lib:      OBJDIR, FIXDIR, libioapi.a
#       clean:    remove .o's, libioapi.a, and executables from OBJDIR
#       rmexe:    remove executables from OBJDIR
#       relink:   rebuild executables from OBJDIR
#       install:  copy "libioapi.a" and executables to $(INSTDIR)
#       dirs:     make OBJDIR and FIXDIR directories
#       fix:      FIXDIR and extended-fixed-source INCLUDE-files
#       gtar:     GZipped tar-file of the source and docs
#       nametest: test of name-mangling compatibility (requires that
#                 libnetcdf.a be manually placed into $(OBJDIR))
#
######################################################################

BASEDIR = /env/proj/coats/ioapi_3
IODIR   = $(BASEDIR)/ioapi
FIXDIR  = $(IODIR)/fixed_src
HTMLDIR = $(BASEDIR)/HTML
TESTDIR = $(BASEDIR)/iotests
TOOLDIR = $(BASEDIR)/m3tools
NOTDIR  = $(BASEDIR)/notcdf
OBJDIR  = $(BASEDIR)/$(BIN)
INSTDIR = $(INSTALL)/$(BIN)
#
#      ----------------------   TOP-LEVEL TARGETS:   ------------------
#
all:  dirs fix
	(cd $(IODIR)   ; make all)
	(cd $(NOTDIR)  ; make all)
	(cd $(TOOLDIR) ; make all)
	(cd $(TESTDIR) ; make all)

cpl:  dirs fix
	(cd $(IODIR)   ; make -f Makefile.cpl all)
	(cd $(NOTDIR)  ; make all)
	(cd $(TOOLDIR) ; make -f Makefile.cpl all)
	(cd $(TESTDIR) ; make -f Makefile.cpl all)

nocpl:  dirs fix
	(cd $(IODIR)   ; make -f Makefile.nocpl all)
	(cd $(NOTDIR)  ; make all)
	(cd $(TOOLDIR) ; make -f Makefile.nocpl all)
	(cd $(TESTDIR) ; make -f Makefile.nocpl all)

f77:  dirs fix
	(cd $(IODIR)   ; make all)
	(cd $(NOTDIR)  ; make all)
	(cd $(TOOLDIR) ; make f77)

f77cpl:  dirs fix
	(cd $(IODIR)   ; make -f Makefile.cpl all)
	(cd $(NOTDIR)  ; make all)
	(cd $(TOOLDIR) ; make -f Makefile.cpl f77)

f77nocpl:  dirs fix
	(cd $(IODIR)   ; make -f Makefile.nocpl all)
	(cd $(NOTDIR)  ; make all)
	(cd $(TOOLDIR) ; make -f Makefile.nocpl f77)

clean:
	(cd $(IODIR)   ; make clean)
	(cd $(NOTDIR)  ; make clean)
	(cd $(TOOLDIR) ; make clean)
	(cd $(TESTDIR) ; make clean)

relink:
	(cd $(TOOLDIR) ; make -i rmexe; make)
	(cd $(TESTDIR) ; make -i rmexe; make)

install: $(INSTDIR)
	echo "Installing I/O API and M3TOOLS in $(INSTDIR)"
	(cd $(IODIR)   ; make install)
	(cd $(NOTDIR)  ; make install)
	(cd $(TOOLDIR) ; make install)

dirs: $(OBJDIR) $(FIXDIR)

fix:  dirs
	(cd $(IODIR)   ; make fixed_src)

gtar:
	cd $(BASEDIR); \
gtar cvfz ioapi_3.tar.gz --dereference -X $(BASEDIR)/exclude \
Makefile ioapi HTML m3tools iotests notcdf

lib:  dirs
	(cd $(IODIR)   ; make all)

not:  dirs
	(cd $(NOTDIR)   ; make all)

nametest:  lib $(OBJDIR)/libnetcdf.a

$(FIXDIR):
	mkdir $(FIXDIR)

$(OBJDIR):
	mkdir $(OBJDIR)

